import openai

openai_key = "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"
openai.api_key = openai_key

def prompt_making():
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "user", "content": "write a code for python"},
        ]
    )

    # Extract and print the poem generated by the model
    poem = response['choices'][0]['message']['content']
    print(poem)

prompt_making()
